const DIFFICULTY = 5;
const MINE_RATE = 60000;
const INITIAL_BALANCE = 500;
const MINING_REWARD = 50;
const GCM_SERVER_API_KEY = 'AIzaSyB7Z0EENNEcPnccaJILBXmRM-6xgiY_ass';

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  INITIAL_BALANCE,
  MINING_REWARD,
  GCM_SERVER_API_KEY
};
